spring:
  application:
    name: TaleAdventure

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    hibernate:
      #   spring.jpa.hibernate.ddl-auto의 옵션
      #      update: 기존의 스키마를 유지하며 JPA에 의해 변경된 부분만 추가한다.
      #      validate: 엔티티와 테이블이 정상적으로 매핑되어있는지만 검증한다.
      #      create: 기존에 존재하는 스키마를 삭제하고 새로 생성한다.
      #      create-drop: 스키마를 생성하고 애플리케이션이 종료될 때 삭제한다.
      #      none: 초기화 동작을 하지 않는다.
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

#jwt:
#  secret-key: ${JWT_SECRET}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
